name: generate Jokes

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  

jobs:
  get-joke:
    runs-on: ubuntu-latest
    steps:
      - name: Make API request
        run: |
          curl --location --request POST 'https://api.openai.com/v1/engines/davinci-codex/completions' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}' \
          --data-raw '{
              "prompt": "3 jokes related to software engineering. Put them in a JS array.",
              "temperature": 0.5,
              "max_tokens": 50,
              "n": 1,
              "stop": "\n"
          }' > response.json
      
      - name: Parse response
        run: echo $(jq -r '.choices[0].text' response.json)


