name: generate Jokes
'on':
  schedule:
    - cron: 0 */24 * * *
  workflow_dispatch: null
jobs:
  get-joke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: location and list files
        run : |
          pwd
          ls
          
      - name: Make API request
        run: >
          curl --location --request POST
          'https://api.openai.com/v1/chat/completions' \

          --header 'Content-Type: application/json' \

          --header 'Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}' \

          --data-raw '{
             "model": "gpt-3.5-turbo",
             "messages": [{"role": "user", "content": "Give me four jokes related to software engineering or cyber security "}],
              "temperature": 0.7
          }' >> jokes.txt
          
      - name:  Print response
        run: cat jokes.txt
        
      - name: Concatenate response to readme.md file
        run: cat ReadMe.md jokes.txt > ReadMe.md
        
      - name: Add response file
        run: git add .
      
      - name: push
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.ACTIONS }}
          push-branch: 'main'
          commit-message: 'publish'
          force-add: 'true'
          name: Lion Tamer
#           email: yad
        
#       - name: Commit changes
#         run: |
#           git config --local user.email "action@github.com"
#           git config --local user.name "GitHub Action"
#           git commit -m "Add response data" -a
#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: '${{ secrets.ACTIONS }}'
