name: generate Jokes
'on':
  schedule:
    - cron: 0 */24 * * *
  workflow_dispatch: null
jobs:
  get-joke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: location and list files
        run : |
          pwd
          ls
      - name: add a line
        run: echo "" >> ReadMe.md
  
      - name : add time stamp
        run: echo date >> ReadMe.md
        
      - name: Make API request
        run: |
          api_response=$(curl --location --request POST \
            'https://api.openai.com/v1/chat/completions' \
            --header 'Content-Type: application/json' \
            --header 'Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}' \
            --data-raw '{
              "model": "gpt-3.5-turbo",
              "messages": [{"role": "user", "content": "Give me four jokes related to software engineering or cyber security "}],
              "temperature": 0.7
            }')
          content_value=$(echo "$api_response" | jq -r '.choices[0].message.content')
          echo "$content_value" >> ReadMe.md
          
#       - name:  Print response
#         run: cat jokes.txt
        
#       - name: Concatenate response to readme.md file
#         run: cat jokes.txt >> ReadMe.md
        
      - name: Add response file
        run: git add .
      
      - name: push
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.ACTIONS }}
          push-branch: 'main'
          commit-message: 'publish'
          force-add: 'true'
          name: Lion Tamer

