name: generate Jokes
'on':
  schedule:
    - cron: 0 */24 * * *
  workflow_dispatch: null
jobs:
  get-joke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Stash any changes
        run: git stash
      
      - name: Pull latest changes
        run: git pull
        
      - name: location and list files
        run: |
          pwd
          ls
        
      - name: Make API request to fetch jokes
        run: |
          joke_response=$(curl -H "Accept: application/json" https://icanhazdadjoke.com/)
          joke=$(echo "$joke_response" | jq -r '.joke')

          echo " " > jokes.md
          echo "$joke" >> jokes.md
          echo " " >> jokes.md
          echo "[ " >> jokes.md
          echo "$(date)" >> jokes.md
          echo " ]" >> jokes.md
      
      - name: Add response file
        run: git add .
      
      - name: push
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.ACTIONS }}
          push-branch: 'main'
          commit-message: 'publish'
          force-add: 'true'
          name: Lion Tamer
