name: Enforce PR Branch

on:
  pull_request:
    branches:
      - main

jobs:
  enforce-pr-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from dev branch
        run: |
          if [[ "${{ github.head_ref }}" != "dev" ]]; then
            echo "Pull requests must be from the 'dev' branch."
            exit 1
          fi
